import './bootstrap';
import './pwa';

import Alpine from 'alpinejs';
import { Workbox } from 'workbox-window';

window.Alpine = Alpine;

// ── PWA: register the service worker (generated by vite-plugin-pwa) ──
if ('serviceWorker' in navigator) {
    window.addEventListener('load', function () {
        const wb = new Workbox('/sw.js');
        wb.register().catch(function (error) {
            console.log('Service Worker registration failed (run `npm run build` first):', error);
        });
    });
}

// ── PWA install prompt ──
window.deferredPrompt = null;
window.addEventListener('beforeinstallprompt', (e) => {
    e.preventDefault();
    window.deferredPrompt = e;
    const installBtn = document.getElementById('installPwaBtn');
    if (installBtn) {
        installBtn.style.display = 'flex';
    }
});

document.addEventListener('click', (e) => {
    if (!e.target.closest('#installPwaBtn') || !window.deferredPrompt) return;
    window.deferredPrompt.prompt();
    window.deferredPrompt.userChoice.then((choiceResult) => {
        if (choiceResult.outcome === 'accepted') {
            console.log('User accepted PWA install');
        } else {
            console.log('User dismissed PWA install');
        }
        window.deferredPrompt = null;
        const installBtn = document.getElementById('installPwaBtn');
        if (installBtn) installBtn.style.display = 'none';
    });
});

// ── App installed event ──
window.addEventListener('appinstalled', () => {
    console.log('COMPASS app installed successfully');
    window.deferredPrompt = null;
    const installBtn = document.getElementById('installPwaBtn');
    if (installBtn) {
        installBtn.style.display = 'none';
    }
});

// ── Network status indicators ──
function setOfflineUI(offline) {
    document.body.classList.toggle('offline-mode', offline);
    const offlineBanner = document.getElementById('offlineBanner');
    if (offlineBanner) {
        offlineBanner.style.display = offline ? 'block' : 'none';
    }
}

window.addEventListener('online', () => setOfflineUI(false));
window.addEventListener('offline', () => setOfflineUI(true));
setOfflineUI(!navigator.onLine);

Alpine.start();