@extends('layouts.app')
@section('title','Operations Reports - COMPASS')
@section('content')
<link rel="stylesheet" href="{{ asset('css/moderator-operations.css') }}?v={{ filemtime(public_path('css/moderator-operations.css')) }}">
@php $tab=in_array(request('tab'),['operations','safety','activity'])?request('tab'):'operations'; $report=$roleReport; @endphp
<link rel="stylesheet" href="{{ asset('css/dashboard-overview.css') }}?v={{ filemtime(public_path('css/dashboard-overview.css')) }}">
<section class="mo-page">
<header class="mo-heading"><div><h1>Reports</h1><p>Operational records, emergency history and one centralized Activity Log.</p></div><a class="mo-button secondary" href="{{ route('moderator.reports.export',request()->except(['cases_page','emergency_page','queue_page','activity_page'])) }}">Export filtered CSV</a></header>
@if(session('success'))<p role="status" class="mo-card">{{ session('success') }}</p>@endif
@if($errors->any())<div class="mo-card" role="alert">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
<form method="GET" class="mo-card mo-filters" aria-label="Report filters">
<input type="hidden" name="tab" value="{{ $tab }}">
<div class="mo-range"><label for="report-range">Date Range (Philippine Time)</label><input id="report-range" type="text" readonly value="{{ $report['from'] }} to {{ $report['to'] }}" aria-haspopup="dialog" style="cursor:pointer"><input type="hidden" id="date-range-value" name="date_range" value="{{ $report['from'] }} to {{ $report['to'] }}"></div>
<div><label for="case-status">Case Status</label><select name="case_status" id="case-status"><option value="">All</option>@foreach(['waiting','helper_assigned','active','completed','evaluated','cancelled','no_show'] as $s)<option value="{{ $s }}" @selected(request('case_status')===$s)>{{ ucwords(str_replace('_',' ',$s)) }}</option>@endforeach</select></div>
<div><label for="emergency-status">Emergency Status</label><select name="emergency_status" id="emergency-status"><option value="">All</option>@foreach(['active','pending','notified','acknowledged','escalated','referred','resolved','closed','cancelled'] as $s)<option value="{{ $s }}" @selected(request('emergency_status')===$s)>{{ ucfirst($s) }}</option>@endforeach</select></div>
<div><label for="priority">Priority</label><select name="priority" id="priority"><option value="">All</option>@foreach(['emergency','high','moderate','low'] as $s)<option @selected(request('priority')===$s)>{{ $s }}</option>@endforeach</select></div>
<div><label for="archive-filter">History</label><select name="archive" id="archive-filter">@foreach(['all'=>'All records','current'=>'Not archived','archived'=>'Archived only'] as $value=>$label)<option value="{{ $value }}" @selected(request('archive','all')===$value)>{{ $label }}</option>@endforeach</select></div>
@if($tab==='activity')<div><label for="activity-type">Activity type</label><select name="activity" id="activity-type"><option value="">All</option>@foreach(['cases','emergencies','queue','actions'] as $s)<option @selected(request('activity')===$s)>{{ $s }}</option>@endforeach</select></div><div><label for="activity-search">Activity / actor</label><input name="search" id="activity-search" value="{{ request('search') }}" maxlength="100"></div>@endif
<button class="mo-button">Apply</button><a class="mo-button secondary" href="{{ route('moderator.reports',['tab'=>$tab]) }}">Reset</a>
</form>
<section class="mo-card"><h2>Report Summary</h2><div class="mo-kpis">@foreach(['Cases in period'=>'Total cases','Completed cases'=>'Completed','Pending requests'=>'Pending','Emergencies'=>'Emergencies'] as $key=>$label)<div class="mo-kpi {{ $key==='Emergencies'?'danger':($key==='Pending requests'?'warning':'') }}"><strong>{{ $report['summary'][$key] }}</strong><span>{{ $label }}</span></div>@endforeach</div></section>
<nav class="mo-tabs" aria-label="Report groups">@foreach(['operations'=>'Operational Activity','safety'=>'Emergency & Safety','activity'=>'Activity Log'] as $value=>$label)<a href="{{ route('moderator.reports',array_merge(request()->except(['cases_page','queue_page','emergency_page','activity_page']),['tab'=>$value])) }}" @if($tab===$value) aria-current="page" @endif>{{ $label }}</a>@endforeach</nav>
@if($tab!=='activity')<section class="mo-card"><h2>{{ $tab==='safety'?'Emergency overview':'Case overview' }}</h2><div class="mo-charts">@foreach(($tab==='safety'?['Emergency status','Emergency priority']:['Cases by status','Case categories']) as $title)<x-dashboard-chart :chart="['title'=>$title,'values'=>$report['groups'][$title],'definition'=>'Actual records in the selected Philippine Time date range.']" />@endforeach</div>@if($tab==='safety')<p class="mo-muted">Acknowledgment: {{ $report['summary']['Emergency acknowledgment time'] }} | Resolution: {{ $report['summary']['Emergency resolution time'] }} | Unresolved: {{ $report['summary']['Unresolved emergencies'] }}</p>@endif</section>@endif
@foreach($report['tables'] as $table)@if($table['group']===$tab || ($tab==='operations' && $table['group']==='operations'))
<section class="mo-card"><h2>{{ $table['title'] }}</h2><div class="mo-table-wrap"><table class="mo-table"><thead><tr>@foreach($table['columns'] as $column)<th>{{ $column }}</th>@endforeach @if($table['type'])<th>History action</th>@endif</tr></thead><tbody>@forelse($table['records'] as $record)<tr>@foreach(($table['format'])($record) as $value)<td>{{ $value }}</td>@endforeach
@if($table['type'])<td>@php $status=$record->session_status ?? $record->request_status ?? $record->status; $kind=$table['type']==='emergency'?$record->source:$table['type']; @endphp
@if(in_array($status,['completed','evaluated','cancelled','expired','no_show','resolved','closed']))<form method="POST" action="{{ route('moderator.archive.store') }}">@csrf<input type="hidden" name="record_type" value="{{ $kind }}"><input type="hidden" name="record_id" value="{{ $record->id }}"><input type="hidden" name="restore" value="{{ $record->archived_at?1:0 }}"><button class="text-green-700 underline">{{ $record->archived_at?'Restore history':'Archive' }}</button></form>@else<span class="mo-muted">Active record</span>@endif</td>@endif</tr>@empty<tr><td colspan="{{ count($table['columns'])+1 }}" class="mo-empty">No records match these filters.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $table['records']->links() }}</div></section>
@endif
@endforeach
</section>
<dialog class="mo-dialog" id="range-dialog"><form method="dialog"><h2 class="font-semibold mb-4">Date Range (Philippine Time)</h2><div class="mo-filters"><div><label for="range-start">Start date</label><input id="range-start" type="date" value="{{ $report['from'] }}" required></div><div><label for="range-end">End date</label><input id="range-end" type="date" value="{{ $report['to'] }}" required></div></div><p id="range-error" role="alert" class="text-red-700 text-sm mt-2"></p><div class="mo-actions"><button class="mo-button" id="range-save" type="button">Use date range</button><button class="mo-button secondary" formnovalidate>Cancel</button></div></form></dialog>
<script>
const rangeDialog=document.getElementById('range-dialog');
document.getElementById('report-range').addEventListener('click',()=>rangeDialog.showModal());
document.getElementById('report-range').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();rangeDialog.showModal();}});
document.getElementById('range-save').addEventListener('click',()=>{const a=document.getElementById('range-start').value,b=document.getElementById('range-end').value;if(!a||!b||a>b){document.getElementById('range-error').textContent='Choose valid dates with the end on or after the start.';return;}document.getElementById('date-range-value').value=a+' to '+b;document.getElementById('report-range').value=a+' to '+b;rangeDialog.close();});
</script>
@endsection
