<?php
namespace App\Support;

final class UiIcon
{
    private const LEGACY = [
        "\u{23F0}" => "fa-clock",
        "\u{23F1}" => "fa-stopwatch",
        "\u{23F3}" => "fa-hourglass-half",
        "\u{23F8}" => "fa-pause",
        "\u{2605}" => "fa-star",
        "\u{2606}" => "fa-star",
        "\u{26A0}" => "fa-triangle-exclamation",
        "\u{26A1}" => "fa-bolt",
        "\u{2705}" => "fa-circle-check",
        "\u{2713}" => "fa-check",
        "\u{2715}" => "fa-xmark",
        "\u{274C}" => "fa-circle-xmark",
        "\u{1F305}" => "fa-sun",
        "\u{1F319}" => "fa-moon",
        "\u{1F31F}" => "fa-star",
        "\u{1F32C}" => "fa-wind",
        "\u{1F33F}" => "fa-leaf",
        "\u{1F389}" => "fa-star",
        "\u{1F399}" => "fa-microphone",
        "\u{1F3AC}" => "fa-video",
        "\u{1F3C1}" => "fa-flag-checkered",
        "\u{1F441}" => "fa-eye",
        "\u{1F448}" => "fa-arrow-left",
        "\u{1F465}" => "fa-users",
        "\u{1F499}" => "fa-heart",
        "\u{1F49A}" => "fa-heart",
        "\u{1F49C}" => "fa-heart",
        "\u{1F4AA}" => "fa-dumbbell",
        "\u{1F4AC}" => "fa-comments",
        "\u{1F4C4}" => "fa-file-lines",
        "\u{1F4C5}" => "fa-calendar",
        "\u{1F4CA}" => "fa-chart-column",
        "\u{1F4CB}" => "fa-clipboard-list",
        "\u{1F4D3}" => "fa-book",
        "\u{1F4D6}" => "fa-book-open",
        "\u{1F4D8}" => "fa-book",
        "\u{1F4DA}" => "fa-book-open",
        "\u{1F4DD}" => "fa-pen-to-square",
        "\u{1F4E2}" => "fa-bullhorn",
        "\u{1F4EC}" => "fa-envelope-open",
        "\u{1F504}" => "fa-arrows-rotate",
        "\u{1F50D}" => "fa-magnifying-glass",
        "\u{1F514}" => "fa-bell",
        "\u{1F516}" => "fa-bookmark",
        "\u{1F525}" => "fa-fire",
        "\u{1F534}" => "fa-circle",
        "\u{1F539}" => "fa-circle",
        "\u{1F550}" => "fa-clock",
        "\u{1F5D3}" => "fa-calendar-days",
        "\u{1F60A}" => "fa-face-laugh",
        "\u{1F60C}" => "fa-face-smile",
        "\u{1F610}" => "fa-face-meh",
        "\u{1F614}" => "fa-face-frown",
        "\u{1F61F}" => "fa-face-frown",
        "\u{1F622}" => "fa-face-sad-tear",
        "\u{1F630}" => "fa-face-frown",
        "\u{1F634}" => "fa-bed",
        "\u{1F642}" => "fa-face-smile",
        "\u{1F645}" => "fa-ban",
        "\u{1F6A8}" => "fa-triangle-exclamation",
        "\u{1F6D1}" => "fa-hand",
        "\u{1F6DF}" => "fa-life-ring",
        "\u{1F7E2}" => "fa-circle",
        "\u{1F91D}" => "fa-handshake",
        "\u{1F9D8}" => "fa-spa",
        "\u{1F9F0}" => "fa-toolbox",
        "\u{1FAA8}" => "fa-mountain",
        "\u{1FAC2}" => "fa-hands-holding-circle",
    ];

    // Aliases preserve legacy stored icon values; all screens render one outline family.
    private const GLYPHS = [
        'bars' => 'menu',
        'paper-plane' => 'send',
        'activity' => 'activity',
        'address-card' => 'badge',
        'alert-circle' => 'alert-circle',
        'archive' => 'archive',
        'arrow-down' => 'arrow-down',
        'arrow-left' => 'arrow-left',
        'arrow-right' => 'arrow-right',
        'arrow-up' => 'arrow-up',
        'arrows-rotate' => 'refresh',
        'audit-log' => 'audit-log',
        'backup' => 'backup',
        'badge' => 'badge',
        'ban' => 'ban',
        'bar-chart' => 'bar-chart',
        'bed' => 'bed',
        'bell' => 'bell',
        'bolt' => 'bolt',
        'book' => 'book-open',
        'book-open' => 'book-open',
        'bookmark' => 'bookmark',
        'box-archive' => 'archive',
        'calendar' => 'calendar',
        'calendar-alt' => 'calendar',
        'calendar-day' => 'calendar',
        'calendar-days' => 'calendar',
        'calendar-minus' => 'calendar',
        'chart-bar' => 'bar-chart',
        'chart-column' => 'bar-chart',
        'chart-line' => 'chart-line',
        'chart-pie' => 'pie-chart',
        'check' => 'check',
        'check-circle' => 'check-circle',
        'check-double' => 'check-circle',
        'chevron-down' => 'chevron-down',
        'chevron-left' => 'chevron-left',
        'chevron-right' => 'chevron-right',
        'circle' => 'circle',
        'circle-check' => 'check-circle',
        'circle-info' => 'info',
        'circle-xmark' => 'close',
        'clipboard' => 'clipboard',
        'clipboard-check' => 'clipboard',
        'clipboard-list' => 'clipboard',
        'clock' => 'clock',
        'close' => 'close',
        'cog' => 'settings',
        'comment' => 'message',
        'comment-dots' => 'message',
        'comments' => 'message',
        'connection' => 'connection',
        'copy' => 'copy',
        'cpu' => 'cpu',
        'dashboard' => 'dashboard',
        'database' => 'database',
        'download' => 'download',
        'dumbbell' => 'toolbox',
        'edit' => 'edit',
        'exchange-alt' => 'connection',
        'exclamation-triangle' => 'warning',
        'external-link' => 'external-link',
        'external-link-alt' => 'external-link',
        'eye' => 'eye',
        'eye-off' => 'eye-off',
        'face-frown' => 'frown',
        'face-laugh' => 'smile',
        'face-meh' => 'neutral',
        'face-sad-tear' => 'frown',
        'face-smile' => 'smile',
        'facebook' => 'globe',
        'file-alt' => 'file-text',
        'file-csv' => 'file-spreadsheet',
        'file-lines' => 'file-text',
        'file-pdf' => 'file-text',
        'file-shield' => 'shield',
        'file-spreadsheet' => 'file-spreadsheet',
        'file-text' => 'file-text',
        'filter' => 'filter',
        'fire' => 'fire',
        'flag' => 'flag',
        'flag-checkered' => 'flag',
        'folder' => 'folder',
        'folder-check' => 'folder-check',
        'folder-open' => 'folder',
        'frown' => 'frown',
        'globe' => 'globe',
        'graduation' => 'graduation',
        'graduation-cap' => 'graduation',
        'hand' => 'hand',
        'hands-holding-circle' => 'heart',
        'handshake' => 'connection',
        'heart' => 'heart',
        'heart-pulse' => 'heart-pulse',
        'heartbeat' => 'heart-pulse',
        'help' => 'help',
        'home' => 'home',
        'hourglass' => 'hourglass',
        'hourglass-half' => 'hourglass',
        'id-badge' => 'badge',
        'inbox' => 'inbox',
        'info' => 'info',
        'instagram' => 'globe',
        'key' => 'key',
        'layers' => 'layers',
        'leaf' => 'leaf',
        'life-ring' => 'life-ring',
        'list' => 'list',
        'list-check' => 'clipboard',
        'list-ul' => 'list',
        'lock' => 'lock',
        'logout' => 'logout',
        'magnifying-glass' => 'search',
        'megaphone' => 'megaphone',
        'memory' => 'memory',
        'menu' => 'menu',
        'message' => 'message',
        'microphone' => 'microphone',
        'monitor' => 'monitor',
        'moon' => 'moon',
        'more-horizontal' => 'more-horizontal',
        'mountain' => 'mountain',
        'network' => 'network',
        'neutral' => 'neutral',
        'palette' => 'palette',
        'panel-left' => 'panel-left',
        'pause' => 'pause',
        'pen-to-square' => 'edit',
        'phone' => 'phone',
        'phone-alt' => 'phone',
        'phone-off' => 'phone-off',
        'phone-slash' => 'phone-off',
        'pie-chart' => 'pie-chart',
        'play' => 'play',
        'play-circle' => 'play-circle',
        'plug' => 'plug',
        'plus' => 'plus',
        'printer' => 'printer',
        'redo' => 'refresh',
        'refresh' => 'refresh',
        'role' => 'role',
        'rotate-left' => 'undo',
        'save' => 'save',
        'search' => 'search',
        'send' => 'send',
        'server' => 'server',
        'settings' => 'settings',
        'share' => 'share',
        'share-nodes' => 'share',
        'shield' => 'shield',
        'shield-alt' => 'role',
        'shield-halved' => 'role',
        'shuffle' => 'shuffle',
        'sign-in-alt' => 'arrow-right',
        'sign-out-alt' => 'logout',
        'sliders' => 'sliders',
        'sliders-h' => 'sliders',
        'smile' => 'smile',
        'spa' => 'leaf',
        'spinner' => 'spinner',
        'star' => 'star',
        'stop-circle' => 'stop-circle',
        'stopwatch' => 'clock',
        'storage' => 'storage',
        'stream' => 'list',
        'sun' => 'sun',
        'sync' => 'refresh',
        'sync-alt' => 'refresh',
        'th-large' => 'dashboard',
        'times' => 'close',
        'times-circle' => 'close',
        'toggle' => 'toggle',
        'toggle-on' => 'toggle',
        'toolbox' => 'toolbox',
        'trash' => 'trash',
        'trash-alt' => 'trash',
        'tree' => 'leaf',
        'triangle-exclamation' => 'warning',
        'twitter' => 'globe',
        'undo' => 'undo',
        'upload' => 'upload',
        'user' => 'user',
        'user-check' => 'user-check',
        'user-circle' => 'user',
        'user-cog' => 'users',
        'user-edit' => 'edit',
        'user-minus' => 'user-minus',
        'user-plus' => 'user-plus',
        'users' => 'users',
        'users-cog' => 'users',
        'video' => 'video',
        'warning' => 'warning',
        'water' => 'water',
        'wind' => 'wind',
        'xmark' => 'close',
        'youtube' => 'globe',
    ];

    public static function glyph(?string $value): string
    {
        $value = trim($value ?? '');
        if (isset(self::GLYPHS[$value])) return self::GLYPHS[$value];
        $legacy = self::resolve($value);
        preg_match_all('/\bfa-([a-z0-9-]+)/', $legacy, $matches);
        foreach ($matches[1] as $name) {
            if (isset(self::GLYPHS[$name])) return self::GLYPHS[$name];
        }
        return 'info';
    }

    public static function resolve(?string $value): string
    {
        $value = str_replace("\u{FE0F}", '', trim($value ?? ''));
        if (isset(self::LEGACY[$value])) return 'fas '.self::LEGACY[$value];
        if (preg_match('/^(?:(?:fas|far|fa-solid|fa-regular) )?fa-[a-z0-9-]+$/D', $value)) {
            return str_starts_with($value, 'fa-') && !str_contains($value, ' ') ? 'fas '.$value : $value;
        }
        return 'fas fa-circle-info';
    }
}
